[versions]
#jetbrains
kotlin = "1.9.0"
kotlinxSerializationJson = "1.5.1"
#KSP
ksp = "1.9.0-1.0.12"
#AndroidX
androidx-constraintlayout = "2.1.4"
androidx-swiperefreshlayout = "1.1.0"
androidx-lifecycleprocess = "2.6.1"
#Eventbus
eventbus = "3.3.1"
#Room
room = "2.6.0-alpha03"
#Simple Mobile Tools
simple-commons = "b72ded2a75"
android-smsmms = "c3e678befd"
indicator-fast-scroll = "4524cd0b61"
#Gradle
gradlePlugins-agp = "8.11.0"
#build
app-build-compileSDKVersion = "35"
app-build-targetSDK = "35"
app-build-minimumSDK = "23"
app-build-javaVersion = "VERSION_17"
app-build-kotlinJVMTarget = "17"
#Helpers
ez-vcard = "0.11.3"
shortcut-badger = "1.1.22"
#versioning
app-version-appId = "com.simplemobiletools.smsmessenger"
app-version-versionCode = "85"
app-version-versionName = "5.19.3"
[libraries]
javax-servlet = { module = "javax.servlet:javax.servlet-api", version = "4.0.1" }
jetty-server = { module = "org.eclipse.jetty:jetty-server", version = "8.1.21.v20160908" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version = "32.6.0" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
#AndroidX
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycleprocess" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
#Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
#Simple Mobile Tools
simple-mobile-tools-commons = { module = "com.github.SimpleMobileTools:Simple-Commons", version.ref = "simple-commons" }
indicator-fast-scroll = { module = "com.github.tibbi:IndicatorFastScroll", version.ref = "indicator-fast-scroll" }
android-smsmms = { module = "com.github.tibbi:android-smsmms", version.ref = "android-smsmms" }
#EventBus
eventbus = { module = "org.greenrobot:eventbus", version.ref = "eventbus" }
#Helpers
ez-vcard = { module = "com.googlecode.ez-vcard:ez-vcard", version.ref = "ez-vcard" }
shortcut-badger = { module = "me.leolin:ShortcutBadger", version.ref = "shortcut-badger" }
#Kotlin
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime",
]
[plugins]
google-services = { id = "com.google.gms.google-services", version = "4.4.0" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
android = { id = "com.android.application", version.ref = "gradlePlugins-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
